services:
  config-server:
    build: .
    container_name: config-server
    ports:
      - '8888:8888'
    networks:
      - ms-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8888/actuator']
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s

networks:
  ms-network:
    driver: bridge
    name: ms-network
